language: java
jdk:
  - oraclejdk8
deploy:
  branches:
    only:
      - master
  deploy:
   provider: heroku
   api-key:
    secure: $HEROKU_API_KEY
   app:
    master: ci-spring-boot-data-rest-react
