language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api-key:
  secure: $HEROKU_API_KEY
  branches:
    only:
      - master
      - stage
  app:
    master: ci-spring-boot-data-rest-react
    stage: ci-spring-boot-data-rest-stage
